In [4]:
import pandas as pd
# the object type here is Dataframe

df = pd.read_csv('pokemon_data.csv')

df_xlsx = pd.read_excel('pokemon_data.xlsx')

df_txt = pd.read_csv('pokemon_data.txt', delimiter='\t') # tab-separated file

# print(df) <- all data
print(df.head(3)) # top 3 rows
print(df.tail(3)) # bottom 3 rows

   #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80

   Generation  Legendary
0           1      False
1           1      False
2           1      False
       #                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170
799  721            Volcanion     Fire  Water  80     110      120      130

     Sp. Def  Speed  Generation  Legendary
797      130     70           6       True
798      130     80           6       True
799       90     70           6       True

In [16]:
## Read Headers
print(df.columns)

## Read each Column
print(df['Name'][0:3]) # top 5
print(df[['Name', 'Type 1', 'HP']][0:3]) # multiple columns

## Read Each Row
print(df.iloc[1]) # iloc means integer location, here it pull 1 row
print(df.iloc[1:4])

for index, row in df.iterrows():
    print(index, row['Name'])
    
print(df.loc[df['Type 1'] == "Fire"])

## Read a specific location (Row, Column)
print(df.iloc[2,1]) # 2nd Row, 1st Column

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
0    Bulbasaur
1      Ivysaur
2     Venusaur
Name: Name, dtype: object
        Name Type 1  HP
0  Bulbasaur  Grass  45
1    Ivysaur  Grass  60
2   Venusaur  Grass  80
#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object
   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122

   Sp. Def  Speed  Generation  Legendary
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
       #                       Name Type 1    Type 2   HP  Attack  Defense  \
4      4                 Charmander   Fire       NaN   39      52       43
5      5                 Charmeleon   Fire       NaN   58      64       58
6      6                  Charizard   Fire    Flying   78      84       78
7      6  CharizardMega Charizard X   Fire    Dragon   78     130      111
8      6  CharizardMega Charizard Y   Fire    Flying   78     104       78
42    37                     Vulpix   Fire       NaN   38      41       40
43    38                  Ninetales   Fire       NaN   73      76       75
63    58                  Growlithe   Fire       NaN   55      70       45
64    59                   Arcanine   Fire       NaN   90     110       80
83    77                     Ponyta   Fire       NaN   50      85       55
84    78                   Rapidash   Fire       NaN   65     100       70
135  126                     Magmar   Fire       NaN   65      95       57
147  136                    Flareon   Fire       NaN   65     130       60
158  146                    Moltres   Fire    Flying   90     100       90
169  155                  Cyndaquil   Fire       NaN   39      52       43
170  156                    Quilava   Fire       NaN   58      64       58
171  157                 Typhlosion   Fire       NaN   78      84       78
236  218                     Slugma   Fire       NaN   40      40       40
237  219                   Magcargo   Fire      Rock   50      50      120
259  240                      Magby   Fire       NaN   45      75       37
263  244                      Entei   Fire       NaN  115     115       85
270  250                      Ho-oh   Fire    Flying  106     130       90
276  255                    Torchic   Fire       NaN   45      60       40
277  256                  Combusken   Fire  Fighting   60      85       60
278  257                   Blaziken   Fire  Fighting   80     120       70
279  257      BlazikenMega Blaziken   Fire  Fighting   80     160       80
352  322                      Numel   Fire    Ground   60      60       40
353  323                   Camerupt   Fire    Ground   70     100       70
354  323      CameruptMega Camerupt   Fire    Ground   70     120      100
355  324                    Torkoal   Fire       NaN   70      85      140
435  390                   Chimchar   Fire       NaN   44      58       44
436  391                   Monferno   Fire  Fighting   64      78       52
437  392                  Infernape   Fire  Fighting   76     104       71
518  467                  Magmortar   Fire       NaN   75      95       67
542  485                    Heatran   Fire     Steel   91      90      106
557  498                      Tepig   Fire       NaN   65      63       45
558  499                    Pignite   Fire  Fighting   90      93       55
559  500                     Emboar   Fire  Fighting  110     123       65
572  513                    Pansear   Fire       NaN   50      53       48
573  514                   Simisear   Fire       NaN   75      98       63
614  554                   Darumaka   Fire       NaN   70      90       45
615  555    DarmanitanStandard Mode   Fire       NaN  105     140       55
616  555         DarmanitanZen Mode   Fire   Psychic  105      30      105
692  631                    Heatmor   Fire       NaN   85      97       66
721  653                   Fennekin   Fire       NaN   40      45       40
722  654                    Braixen   Fire       NaN   59      59       58
723  655                    Delphox   Fire   Psychic   75      69       72
730  662                Fletchinder   Fire    Flying   62      73       55
731  663                 Talonflame   Fire    Flying   78      81       71
735  667                     Litleo   Fire    Normal   62      50       58
736  668                     Pyroar   Fire    Normal   86      68       72
799  721                  Volcanion   Fire     Water   80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
4         60       50     65           1      False
5         80       65     80           1      False
6        109       85    100           1      False
7        130       85    100           1      False
8        159      115    100           1      False
42        50       65     65           1      False
43        81      100    100           1      False
63        70       50     60           1      False
64       100       80     95           1      False
83        65       65     90           1      False
84        80       80    105           1      False
135      100       85     93           1      False
147       95      110     65           1      False
158      125       85     90           1       True
169       60       50     65           2      False
170       80       65     80           2      False
171      109       85    100           2      False
236       70       40     20           2      False
237       80       80     30           2      False
259       70       55     83           2      False
263       90       75    100           2       True
270      110      154     90           2       True
276       70       50     45           3      False
277       85       60     55           3      False
278      110       70     80           3      False
279      130       80    100           3      False
352       65       45     35           3      False
353      105       75     40           3      False
354      145      105     20           3      False
355       85       70     20           3      False
435       58       44     61           4      False
436       78       52     81           4      False
437      104       71    108           4      False
518      125       95     83           4      False
542      130      106     77           4       True
557       45       45     45           5      False
558       70       55     55           5      False
559      100       65     65           5      False
572       53       48     64           5      False
573       98       63    101           5      False
614       15       45     50           5      False
615       30       55     95           5      False
616      140      105     55           5      False
692      105       66     65           5      False
721       62       60     60           6      False
722       90       70     73           6      False
723      114      100    104           6      False
730       56       52     84           6      False
731       74       69    126           6      False
735       73       54     72           6      False
736      109       66    106           6      False
799      130       90     70           6       True
Venusaur

In [22]:
df.describe() # statistical metrics of data
df.sort_values('Name')
df.sort_values('Name', ascending=False)
df.sort_values(['Type 1', 'HP'], ascending=[True, False]) # sort by Type 1 (ascending), then by HP (descending)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

In [29]:
# new column that sums all the stats
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']